version: '2.1'

services:
  mai-db-1:
    build:
      context: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mysqladmin ping -h localhost --user=stud --password=stud"
      timeout: 20s
      retries: 5
    volumes:
      - maria-db-volume-1:/var/lib/mysql

  mai-db-2:
    build:
      context: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3361:3306
    healthcheck:
      test: "/usr/bin/mysqladmin ping -h localhost --user=stud --password=stud"
      timeout: 20s
      retries: 5
    volumes:
      - maria-db-volume-2:/var/lib/mysql

  mai-db-3:
    build:
      context: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3362:3306
    healthcheck:
      test: "/usr/bin/mysqladmin ping -h localhost --user=stud --password=stud"
      timeout: 20s
      retries: 5
    volumes:
      - maria-db-volume-3:/var/lib/mysql

  proxysql:
    build:
      context: proxysql
    healthcheck:
      test: "/usr/bin/mysql -h 127.0.0.1 -P 6033 --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    networks:
      - arch-network
    ports:
      # Mysql Client Port
      - 6033:6033
      # Mysql Admin Port
      - 6032:6032
    depends_on:
      - mai-db-1
      - mai-db-2
      - mai-db-3
    volumes:
      - proxysql-data:/var/lib/proxysql

  init-db:
    build:
      context: mariadb/data_generator
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_DATABASE=archdb
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
    networks:
      - arch-network
    depends_on:
      proxysql:
        condition: service_healthy

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - arch-network
    volumes:
      - cache:/data

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_INIT_LIMIT: 5
    networks:
      - arch-network

  kafka-node-1:
    image: wurstmeister/kafka
    container_name: kafka-node-1
    depends_on:
      - zookeeper
    ports:
      - 2181:2181
      - 9092:9092
    networks:
      - arch-network
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_HOST_NAME: kafka-node-1
        ADVERTISED_PORT: 9092
        ADVERTISED_HOST_NAME: kafka-node-1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CREATE_TOPICS: "event_server:1:1"

  kafka-writer:
    build:
      context: .
      dockerfile: ./kafka_writer/Dockerfile
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_DATABASE=archdb
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - CACHE=cache:6379
      - QUEUE_HOST=kafka-node-1:9092
      - QUEUE_TOPIC=event_server
      - QUEUE_GROUP_ID=0
    networks:
      - arch-network
    depends_on:
      - mai-db-1
      - mai-db-2
      - mai-db-3
      - proxysql
      - cache
      - kafka-node-1

  auth-service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_DATABASE=archdb
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - CACHE=cache:6379
      - QUEUE_HOST=kafka-node-1:9092
      - QUEUE_TOPIC=event_server
      - QUEUE_GROUP_ID=0
    ports:
      - 8080:8080
    networks:
      - arch-network
    depends_on:
      cache:
        condition: service_started
      proxysql:
        condition: service_healthy

  group-chat-service:
    build:
      context: .
      dockerfile: ./gc_service/Dockerfile
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_DATABASE=archdb
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - AUTH_HOST=auth-service
      - CACHE=cache:6379
      - QUEUE_HOST=kafka-node-1:9092
      - QUEUE_TOPIC=event_server
      - QUEUE_GROUP_ID=0
    ports:
      - 8081:8081
    networks:
      - arch-network
    depends_on:
      proxysql:
        condition: service_healthy

  p2p-service:
    build:
      context: .
      dockerfile: ./p2p_service/Dockerfile
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_DATABASE=archdb
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - AUTH_HOST=auth-service
      - CACHE=cache:6379
      - QUEUE_HOST=kafka-node-1:9092
      - QUEUE_TOPIC=event_server
      - QUEUE_GROUP_ID=0
    ports:
      - 8082:8082
    networks:
      - arch-network
    depends_on:
      proxysql:
        condition: service_healthy


volumes:
  maria-db-volume-1:
  maria-db-volume-2:
  maria-db-volume-3:
  proxysql-data:
  cache:

networks:
  arch-network:
    driver: "bridge"
    external: false
